frac_dic = {
    'Disc_height': 'optic disc height(optic disc vertical diameter)',
    'Disc_width': 'optic disc width(optic disc horizontal  diameter)',
    'Cup_height': 'cup height',
    'Cup_width': 'cup width',
    'CDR_vertical': 'vertical cup-to-disc ratio',
    'CDR_horizontal': 'Horizontal cup-to-disc ratio',
    'Fractal_dimension': 'fractal demission of retina vessels',
    'Vessel_density': 'vessels density',
    'Average_width': 'averge width of vessels',
    'Distance_tortuosity': 'distance tortuosity density of retina vessels',
    'Squared_curvature_tortuosity': 'squared curvature tortuosity of retinal vessels',
    'Tortuosity_density': 'tortuosity density of retinal vessels',
    'Artery_Fractal_dimension': 'fractal dimension of retinal arteries',
    'Artery_Vessel_density': 'density of retinal arteries',
    'Artery_Average_width': 'average width of retinal arteries',
    'Artery_Distance_tortuosity': 'distance tortuosity of retinal arteries',
    'Artery_Squared_curvature_tortuosity': 'squared curvature tortuosity of retinal veins',
    'Artery_Tortuosity_density': 'tortuosity density of  veins',
    'Vein_Fractal_dimension': 'fractal dimension of retinal veins.',
    'Vein_Vessel_density': 'density of retinal veins',
    'Vein_Average_width': 'average width of retinal veins',
    'Vein_Distance_tortuosity': 'distance tortuosity of retinal veins',
    'Vein_Squared_curvature_tortuosity': 'squared curvature tortuosity of retinal veins',
    'Vein_Tortuosity_density': 'tortuosity density of retinal veins',
    'Fractal_dimension_zone_b': 'fractal dimension in Zone B in the retina',
    'Vessel_density_zone_b': 'vessel density in Zone B',
    'Average_width_zone_b': 'average vessel width in Zone B',
    'Distance_tortuosity_zone_b': 'distance tortuosity in Zone B',
    'Squared_curvature_tortuosity_zone_b': 'squared curvature tortuosity in Zone B',
    'Tortuosity_density_zone_b': 'Tortuosity density in Zone B',
    'Artery_Fractal_dimension_zone_b': 'Arterial fractal dimension in Zone B',
    'Artery_Vessel_density_zone_b': 'Artery vessel density in Zone B',
    'Artery_Average_width_zone_b': 'Artery average width in Zone B',
    'Artery_Distance_tortuosity_zone_b': 'Artery distance tortuosity in Zone B',
    'Artery_Squared_curvature_tortuosity_zone_b': 'Artery squared curvature tortuosity in Zone B',
    'Artery_Tortuosity_density_zone_b': 'Artery tortuosity density in Zone B',
    'CRAE_Hubbard_zone_b': 'CRAE Hubbard value in Zone B',
    'CRAE_Knudtson_zone_b': 'CRAE Knudtson value in Zone B',
    'Vein_Fractal_dimension_zone_b': 'Vein fractal dimension in Zone B',
    'Vein_Vessel_density_zone_b': 'Vein vessel density in Zone B',
    'Vein_Average_width_zone_b': 'Vein average width in Zone B',
    'Vein_Distance_tortuosity_zone_b': 'Vein distance tortuosity in Zone B',
    'Vein_Squared_curvature_tortuosity_zone_b': 'Vein squared curvature tortuosity in Zone B',
    'Vein_Tortuosity_density_zone_b': 'Vein tortuosity density in Zone B',
    'CRVE_Hubbard_zone_b': 'CRVE Hubbard value in Zone B',
    'CRVE_Knudtson_zone_b': 'CRVE Knudtson value in Zone B',
    'AVR_Hubbard_zone_b': 'AVR Hubbard ratio in Zone B',
    'AVR_Knudtson_zone_b': 'AVR Knudtson ratio in Zone B',
    'Fractal_dimension_zone_c': 'Fractal dimension in Zone C',
    'Vessel_density_zone_c': 'Vessel density in Zone C',
    'Average_width_zone_c': 'Average vessel width in Zone C',
    'Distance_tortuosity_zone_c': 'Distance tortuosity in Zone C',
    'Squared_curvature_tortuosity_zone_c': 'Squared curvature tortuosity in Zone C',
    'Tortuosity_density_zone_c': 'Tortuosity density in Zone C',
    'Artery_Fractal_dimension_zone_c': 'Arterial fractal dimension in Zone C',
    'Artery_Vessel_density_zone_c': 'Artery vessel density in Zone C',
    'Artery_Average_width_zone_c': 'Artery average width in Zone C',
    'Artery_Distance_tortuosity_zone_c': 'Artery distance tortuosity in Zone C',
    'Artery_Squared_curvature_tortuosity_zone_c': 'Artery squared curvature tortuosity in Zone C',
    'Artery_Tortuosity_density_zone_c': 'Artery tortuosity density in Zone C',
    'CRAE_Hubbard_zone_c': 'CRAE Hubbard value in Zone C',
    'CRAE_Knudtson_zone_c': 'CRAE Knudtson value in Zone C',
    'Vein_Fractal_dimension_zone_c': 'Vein fractal dimension in Zone C',
    'Vein_Vessel_density_zone_c': 'Vein vessel density in Zone C',
    'Vein_Average_width_zone_c': 'Vein average width in Zone C',
    'Vein_Distance_tortuosity_zone_c': 'Vein distance tortuosity in Zone C',
    'Vein_Squared_curvature_tortuosity_zone_c': 'Vein squared curvature tortuosity in Zone C',
    'Vein_Tortuosity_density_zone_c': 'Vein tortuosity density in Zone C',
    'CRVE_Hubbard_zone_c': 'CRVE Hubbard value in Zone C',
    'CRVE_Knudtson_zone_c': 'CRVE Knudtson value in Zone C',
    'AVR_Hubbard_zone_c': 'AVR Hubbard ratio in Zone C',
    'AVR_Knudtson_zone_c': 'AVR Knudtson ratio in Zone C',
    'Average Branch Angle': 'Average Branch Angle of all vessels'
}